### ISSUE TITLE
How to get the title if the JSON Array contains a title like this?

### ISSUE THREAD

**Issue by babyghost-ys** [amirdew/JSON#3]
![screen shot 2017-05-21 at 7 03 22 pm](https://cloud.githubusercontent.com/assets/5141074/26286243/3a6f474e-3e58-11e7-87b3-dbd6fb73a72a.png)

I am trying to use the library to get the title from the above JSON. I tried to use postJSON.getJsonArray().length() to get the length but not successful. l also tried postJSON.key("posts").count() to get the count of array which is also not successful. (postJSON is defined as JSON object).  I guess it's because this JSON contains a text "posts" before JSON array?

I am now using the default JSON support which works. but I would prefer to use your library if possible since it's faster and more stable. 

```
if (jsonStr != null) {
                try {
                    JSONObject jsonObject = new JSONObject(jsonStr);
                    JSONArray postItems = jsonObject.getJSONArray("posts");

                    for (int i = 0; i < postItems.length(); i++) {
                        JSONObject title = postItems.getJSONObject(i);
                        myData.add(title.getString("title"));
                    }
                } catch (JSONException e){

                }
}
```

**Comment by amirdew** [comment]
Hi, 
there is no problem with that, please see sample, I update sample with key in root:

```
JSON products = new JSON(readFileFromAsset("products.json")).key("products");
        for (int i = 0; i < products.count(); i++) {
            JSON productInfo = products.index(i);
            resultText += String.format("\n\n product[%d]: id:%d, name:'%s', price:%.2f, length:%.2f",
                    i,
                    productInfo.key("id").intValue(),
                    productInfo.key("name").stringValue(),
                    productInfo.key("price").doubleValue(),
                    productInfo.key("dimensions").key("length").doubleValue()
            );
        }
```

**Comment by babyghost-ys** [comment]
Thanks for the quick answer, I tried use the following code but still return count 0...

```
 JSON postJSON = new JSON(jsonStr).key("posts");
            Log.d("RESULTS",jsonStr);
            Log.d("how many items", String.valueOf(postJSON.count()));
                for (int i = 0; i < postJSON.count(); i++) {
                    JSON productInfo = postJSON.index(i);
                    Log.d("something",productInfo.key("title").stringValue());

                    myData.add(productInfo.key("title").stringValue());
                }

            return null;
```

**Comment by amirdew** [comment]
Please send your full json string as a file, to check it.

**Comment by babyghost-ys** [comment]
I think you are right. I tried to copy the whole response to your example and it works. but, when I get the string from the internet and put that back _jsonStr_, it causes problems. The way that I fix it, is to convert the _jsonStr_ to a JSONObject first, before using your library.

It works. May be there are no ways to avoid using the Android JSONObject for this weird type of JSON?

Here is the link of the JSON: http://www.car1.hk/category/cat-local/?json=1.


 ```
if (jsonStr != null) {
                try {
                    JSONObject jsonObject = new JSONObject(jsonStr);
                    postJSON = new JSON(jsonObject).key("posts");
                    for (int i = 0; i < postJSON.count(); i++) {
                        myData.add(postJSON.index(i).key("title").stringValue());
                    }
                } catch (JSONException e){

                }
            }

```

**Comment by amirdew** [comment]
There is no difference between the two methods (pass json as string or JSONObject).
Maybe problem caused by your network library.
Try to clear and trim your string before use may solve the problem.
