### ISSUE TITLE
Issues with the index() function not working as expected

### ISSUE THREAD

**Issue by quiquelhappy** [amirdew/JSON#6]
Hello,
I'm having some problems trying to read the data here.
I've tried to use:
`JSON(data).index(0).key("studies").index(0).key("names").key("en").stringValue()`

![image](https://user-images.githubusercontent.com/12534357/56053231-df356d00-5d53-11e9-9c32-1909ef28e397.png)

I believe the problem is near key("studies")**.index(0)**, because I'm able to access key("studies") and read the data, but I cannot access the data inside there because there is no way of knowing previously the key and the index function is apparently not working as expected.

RAW JSON here: https://hastebin.com/raw/iyesevifad

FYI, I'm using Kotlin

**Comment by amirdew** [comment]
Hi, unfortunately, this is not possible now, I can add it in next version,    
but for now, you can do this:   
```kotlin
val studies =  JSON(data).index(0).key("studies")
val firstKey = studies.getJsonObject().keys[0]
studies.key(firstKey).key("names").key("en").stringValue()
```
